name: dataroid_sdk_android
description: Android implementation of Dataroid SDK
version: 4.1.0
homepage: https://www.dataroid.com
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  dataroid_sdk_platform_interface:
    path: ../dataroid_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: dataroid_plugin_flutter
    platforms:
      android:
        package: com.dataroid.dataroid_sdk_android
        pluginClass: DataroidSdkAndroidPlugin
        dartPluginClass: DataroidSdkAndroid

